"""Added stock account

Revision ID: 5bd68dc63479
Revises: 3fd5b6f3011d
Create Date: 2024-01-10 01:15:40.337056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd68dc63479'
down_revision: Union[str, None] = '3fd5b6f3011d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_iia', sa.Boolean(), nullable=False),
    sa.Column('stock_value', sa.DECIMAL(scale=2), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_accounts')
    # ### end Alembic commands ###
